### ISSUE TITLE
Add github Action to Automate testing on main branch and PR's to main branch

### ISSUE THREAD

**Issue by wgarunap** [wgarunap/goconf#16]
Add github Action to Automate testing on main branch and PR's to main branch

```yaml
name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

```
